services:
  api:
    build: ./Dockerfile
    image: igelschnauzen/another_knowledge_base
    ports:
      - 3000:3000
    networks:
      - knowledge_network
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo
    ports:
      - 27018:27018
    volumes:
      - db-volume:/data/db
    networks:
      - knowledge_network

volumes:
  db-volume:
    name: db-volume
    

networks:
  knowledge_network:
    driver: bridge